### ISSUE TITLE
Add a default account for transactions + an option in settings

### ISSUE THREAD

**Issue by prannou** [moneymanagerex/android-money-manager-ex#100]
I think it would be good the allow the user to set a default account in the settings. This account will be used by default when creating a new transaction. I saw that there is an option to show only favorites accounts, but if we use it we can't choose/see other accounts. It would like to set my main accounts as default and still be able to choose an other account when adding a transaction. What do you think ?

If it's OK, I could implement it (but maybe not for the v2.0).

**Comment by MisterY** [comment]
I like that the list of accounts is configurable and it can be made relatively short so that it is easy to select an account. 
Currently there is a setting for filtering the accounts, which is consistent with the desktop version. However, I also have an issue with the way the filter works as it is not flexible enough. 

For the use case here, when another account is needed, too much effort is required to be able to select it. And it breaks the flow as the user has to stop what they are doing and go to settings, adjust, enter the transaction, change the setting back. 
What I think would be a good solution is to be able to expand the list quickly or open a larger selector with all accounts. 

So, thinking of this, here is my suggestion: 
If there is an account filter applied in the settings, add a line at the end of accounts drop down that says "Other..." and which leads to the Accounts list in the Pick mode. There the account is selected and the flow returns to the transaction add / edit screen. 
The pattern for edit vs pick is now used for the currency list, in the open pull requests, and is a great way to communicate what the user is trying to do. 
In Edit mode, there are no selection boxes in the list but the options menu shows up. In Pick mode, single tap selects the item in the list and the context menu is available on long tap. The behaviour can be adjusted but the principle is there. 

Or, we implement quick filters on lists; account selector opens account list directly (no drop down in this case) with the selected filter applied (for example favourites); and there is a quick way to reset the filter (X) and see all the accounts and make a selection. 

This might be more work but avoids creating another setting that applies only to one screen and might be viewed as redundant to a user. 
What do you think?

**Comment by AlessandroLazzari** [comment]
Our goal is to make the porting of the Desktop version. A user who uses MoneyManagerEx PC needs to be have the same functionality as the desktop version, but with the facilities for the use on a smartphone or tablet.
The question of @prannou is not wrong, but I think perhaps it would make sense to discuss transaction template with the team desktop.
I agree with the solution of @MisterY add as the last Item of the dropdown Others...when Accounts are hidden. When this is clicked are loaded all accounts.
I this issue the give it to the milestone 2.1.
What do you think?

**Comment by MisterY** [comment]
I like how we all use "what do you think" at the end. ;)

**Comment by prannou** [comment]
Adding the possibility to choose "Other" to see all the accounts would make it possible to have only one account as favorite and still choose others if necessary, which I think is good. People could make their main account, their only favorite account (so have it selected when creating a new transaction).

My goal here was to make adding a transaction even faster (I think it is important for a mobile app). If people use the same account for the majority of their transactions, they wouldn't have to change this when creating a new transaction.

But I also agree we have to be coherent with the desktop version.

**Comment by MisterY** [comment]
Hm, well, @prannou has a point. The desktop version opens with a blank account field, which is even worse. I agree that a setting where a user could select from the list of all accounts is a good idea in that case.
For me personally this is not an issue as my cash account is at the top of the list and this is the account that I would use by default in any case. And the list allows fairly quick selection. But I see a case when the current options could cause a bit of inconvenience.

So, I support the setting option. If Alessandro agrees, we could go ahead.

So, the default account would have to be checked for existence and added to the filtered list or available accounts?
Should we still add the feature for selection of any account?

**Comment by AlessandroLazzari** [comment]
Ok for the default account in the settings. Obviously, the user can also
choose nothing. If there is a default account in the settings, when the
user makes a new transaction, the application proposes the default
account (similar behavior to the default state or the last payee used in
setting).
For the rest we let the standard behavior of the application, without any
further changes.
Do you all agree? If we all agree, we can proceed with the implementation.

2015-03-30 21:34 GMT+02:00 Alen Siljak <notifications@github.com>:

**Comment by MisterY** [comment]
Yup, that's fine.

**Comment by prannou** [comment]
OK. I'll implement it for the v2.1 and add a pull request when it's done.

**Comment by AlessandroLazzari** [comment]
OK thanks

**Comment by MisterY** [comment]
:+1: 
Now that the state of account groups is saved (collapsed/expanded), it is more convenient to have all accounts visible instead of filtering only to preferred ones.
In that case I experience this issue more and yes, it is really annoying constantly seeing the account that is almost never used. So, bump! This would be quite convenient to have. The sooner the better. :)

**Comment by MisterY** [comment]
One of the alternatives would be also to remember the last used account!

**Comment by MisterY** [comment]
The v2.1.0 is in Alpha stage now and open for merge requests. As usual, the dev branch is to be used for the upcoming version while master is kept stable.
