### ISSUE TITLE
Allow donation from Google Wallet / Play Store balance

### ISSUE THREAD

**Issue by yaomtc** [moneymanagerex/android-money-manager-ex#1035]
Many people use Google's "Opinion Rewards" app to earn small amounts of money for the Google Play Store. I tend to spend this money towards premium versions of apps I like, and if it's supported, as donations. However I'd like to donate this money towards MMEX, this is not currently possible. Is there a way we could have Google Wallet / Play Store payment support added?

**Comment by MisterY** [comment]
Initially the donations were accepted like this. However, due to restrictive policies it is not possible to change the account that was first registered for this purpose. Considering that the mentioned account is a private account of a former project member, this is currently not an option.
If, however, someone figures out a way to do this, please share.

**Comment by yaomtc** [comment]
Here's how the creator of Keepass2Android does it: he created another app for the purpose of accepting donations. However this may not be a very good solution, since it requires installing another app.

https://play.google.com/store/apps/details?id=com.keepass2android.android.donate

Is this the correct information?

https://support.google.com/googleplay/android-developer/answer/6230247?visit_id=1-636100050792475920-2143100386&rd=1

**Comment by MisterY** [comment]
That option might work if the donation app is published from another developer account. As you say, that might be inconvenient. I'll have a look at some point. Thanks.
