### ISSUE TITLE
Unable to download latest stock prices

### ISSUE THREAD

**Issue by NaveenBoggarapu** [moneymanagerex/android-money-manager-ex#1085]
My version is 2016.11.08.945

I have created an investment account and added a stock (SBIN.NS). when I tried to download price for the stock, a message "No price found for symbol SBIN.NS" is being displayed.

I have selected YahooYql as my quote provider and I am able to see quotes for the same symbol at http://finance.yahoo.com/chart/SBIN.NS

This is same with any symbol.

**Comment by MisterY** [comment]
Hi, Naveen, the URL where you are checking is not YQL. The YQL sources are here: https://developer.yahoo.com/yql/

**Comment by NaveenBoggarapu** [comment]
So in my mobile app, which symbol should I give?

What I am saying is, there is a bug in the the application. It is not fetching quotes correctly.

**Comment by MisterY** [comment]
Thanks, I understand what you are saying. What I am saying is: "This is an Open Source project. You are free to correct the issue and submit a pull request. Currently there is nobody else who can do that for you."

**Comment by NaveenBoggarapu** [comment]
Ok.

It seems, the problem is not with the application, not all stock symbols are available with YQL. when tried other stocks (traded in NASDAQ) it is working fine

**Comment by MisterY** [comment]
Why don't you simply change the quotes provider in the settings? You can use the "regular" Yahoo Finance quotes provider. Both are unreliable at times but it seems this is the best that can be done at the moment.

**Comment by NaveenBoggarapu** [comment]
I have tried with all the three providers listed in app(YahooYql, YahooCsv, Morningstar). I might need to added another provider in to code and test it. I will fork it and try.

**Comment by MisterY** [comment]
Ah, OK. Sorry to see that. Which exchanged is the .NS?
Btw, you can see the requesting URLs from the source code. I'm not sure how Yahoo assembles all the various sources to show on the web site.
I have switched to Morningstar because Yahoo prices for ETFs are very unreliable after the working hours (I follow some Australian ETFs). They fall back to a value from some other date.
Thanks for the effort. Unfortunately, I am currently unable to do any Android development but can at least merge any pull requests and occassionally produce and deploy a new build.

**Comment by NaveenBoggarapu** [comment]
It is "National Stock Exchange of India Ltd."

I have looked in to the requesting URLs. Morningstar works fine, but the symbol used by Morningstar and yahoo are different. (Yahoo uses SBIN.NS, where as Morningstar is just SBIN)

One observation is, it would be better if there is an option to change symbol in mobile app, in the current version it is not present. Once you enter a stock, all you can do is Download price, edit price or delete. 

I will plan working on having an option to edit it.

**Comment by MisterY** [comment]
That functionality has been there for over a year. Just go to the Portfolio instead of the Watchlist.

Sent from Yahoo7 Mail on Android 
 
  On Thu, 24 Nov, 2016 at 10:42, NaveenBoggarapu<notifications@github.com> wrote:   
It is "National Stock Exchange of India Ltd."

I have looked in to the requesting URLs. Morningstar works fine, but the symbol used by Morningstar and yahoo are different. (Yahoo uses SBIN.NS, where as Morningstar is just SBIN)

One observation is, it would be better if there is an option to change symbol in mobile app, in the current version it is not present. Once you enter a stock, all you can do is Download price, edit price or delete.

I will plan working on having an option to edit it.

**Comment by NaveenBoggarapu** [comment]
I don't see any option for protfolio/watchlist. 

The way I am seeing them is ,

Home -> "Tap on my account under Investment Accounts"

Correct me If I am wrong.

**Comment by MisterY** [comment]
Right. Just long-press instead of tapping once.

Sent from Yahoo7 Mail on Android 
 
  On Thu, 24 Nov, 2016 at 11:25, NaveenBoggarapu<notifications@github.com> wrote:   
I don't see any option for protfolio/watchlist.

The way I am seeing them is ,

Home -> "Tap on my account under Investment Accounts"

Correct me If I am wrong.

**Comment by NaveenBoggarapu** [comment]
Got it
