### ISSUE TITLE
Replace the numeric input on security price entry

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#1090]
The price/date dialog needs to be redone as a separate activity first.
Then the numeric input can be switched from a dialog to the new input activity.

**Comment by Trainrecktr8** [comment]
thankyou
Adadsphinn Jedi master deadpool TR8NINJA

On Jan 18, 2017 5:57 PM, "Alen Siljak" <notifications@github.com> wrote:

Closed #1090
<https://github.com/moneymanagerex/android-money-manager-ex/issues/1090>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/moneymanagerex/android-money-manager-ex/issues/1090#event-928138481>,
or mute the thread
