### ISSUE TITLE
Transfer to the same account is possible

### ISSUE THREAD

**Issue by prannou** [moneymanagerex/android-money-manager-ex#110]
I realize that it is possible to make a transfer from an account A to the same account A. Is it normal and the same in the desktop version ? The problem is that it appears as a single transaction (credit) in the transaction list.

**Comment by guanlisheng** [comment]
It's abnormal 

LiSheng

**Comment by MisterY** [comment]
We should probably prevent a user to select the same account by removing it from the list of destination accounts when the source account is selected.

**Comment by guanlisheng** [comment]
Yep and totally agree. 

LiSheng

**Comment by AlessandroLazzari** [comment]
It is a bug.

However, the solution to hide the selected account (from or to) is not so
simple, since you have to always update the adapter....with its refresh of
the dropdown...and you have to remember to reset all the accounts if you
change the type of transaction to Transfer a Withdrawal or Deposit.

​​
​
IMHO, the application can give the user a messagebox with a warning that
the account is the same. The result is the same.​
​ ​
​​
And implementation, and much more simple.
This is only my opinion.

**Comment by MisterY** [comment]
Yes, that would have more or less the same result. We should fix the bug first.
If someone wants, they can implement the more complex but user-friendlier version at some point. It would be a good exercise to try to find a patterns for applying filters in similar situations.
