### ISSUE TITLE
Cannot pick remote file when configurationg sync with OneDrive

### ISSUE THREAD

**Issue by tmchanph** [moneymanagerex/android-money-manager-ex#1137]
When tapping the remote file, it doesn't show the OneDrive directory (like with Google Drive) to select te remote file to use. It is throwing an error "ServiceCode Error in function getChildrenSC at 39".

**Comment by andrepg** [comment]
When running on my S7 with Android 7.0, just the line changed to 45

**Comment by mannybiker** [comment]
Same problem here. I found the reason why it only happens on certains OneDrive account. This happens when you have used the feature of adding a shared folder to your OneDrive with the function "Add to my OneDrive". If there is a shared folder "attached" to your personal drive so Money Manager is unable to list the folder and raise the error "in my case is at 45". Hope this could help in the debugging process

**Comment by MisterY** [comment]
Unfortunately, it won't help directly as we don't communicate directly with any of the services. The CloudRail library is handling all the communication with the storage services.
If you can confirm a bug, please report at the CloudRail for Android repository. Thanks!

**Comment by MisterY** [comment]
#1278 is the way forward
