### ISSUE TITLE
1st Account is selected by default even if default account is selected as None

### ISSUE THREAD

**Issue by velmuruganc** [moneymanagerex/android-money-manager-ex#1229]
On clicking + btn in the main screen, new transaction screen displayed with 1st account selected in from account field. Here I feel, it should show just blank field.

![image](https://user-images.githubusercontent.com/29807533/38771081-1f97b8a4-403a-11e8-8bdf-7da1da25b911.png)

![image](https://user-images.githubusercontent.com/29807533/38771098-6372a354-403a-11e8-8553-287d37ec0207.png)

**Comment by velmuruganc** [comment]
I think, account drop down should have blank entry as a first option. Similar to account dropdown in Search screen.
![image](https://user-images.githubusercontent.com/29807533/38771178-fd09294c-403b-11e8-9edf-e23cebeeb3ad.png)

**Comment by velmuruganc** [comment]
It is not a big deal to tap one more time, but it will be confusing user when I am showing up the Edit Screen during Bank SMS transaction. User may think that the received SMS is not belong to the select sms.

**Comment by MisterY** [comment]
That issue could be solved by having a setting for the account to be used for SMS, or reading that information from the received SMS itself. It should not affect those who are not using this functionality.

It would be nice if this was a plugin to MMEX, since it requires an additional permission. Some users were already complaining about it.

And, yes, having to tap one more time *is* a big deal as it is additional effort that does not need to be there. We are supposed to be making things easier, not harder.
Having to tap to change an account is OK, if no default is set. But having to tap *every* time is simply bad user experience.
