### ISSUE TITLE
Issue to read database version 10 (mmex 14.alpha)

### ISSUE THREAD

**Issue by thenotec** [moneymanagerex/android-money-manager-ex#1245]
After upgrade to Ubuntu 18.04 I can't install stable version (dipendences forgotten) but only prerelease package in alpha version. 

Prerelease upgrade database from version 8 to 10 but then mmex Android don't read anymore. 

Have suggestions about?

**Comment by andrepg** [comment]
It seems a little "desync" with MMEX Android and desktop. @MisterY want's to work on some things at database structure, but he asks for some time, since this project it's a hobby.

The suggestions that I have right now is: you can wait and use mmex webapp if you want and it's possible hosting somewhere...

**Comment by thenotec** [comment]
I understand. My wish was to report the bug to you... I can wait. I hope in more luck for mmex in future.

**Comment by andrepg** [comment]
I'm just a contributor, helps how I can. I'm love with this project and desktop version and using it since a year... Desktop has changed a lot lately, and it's hard to mantain these two databases.

Let's keep our finger crossed 😄

**Comment by StefTas5562** [comment]
Is there something new about this issue?

**Comment by wolfsolver** [comment]
Need to be closed since new 2023 version is aligned with desktop version 1.7.0
