### ISSUE TITLE
Updating currencies exchange rates 

### ISSUE THREAD

**Issue by mr10008** [moneymanagerex/android-money-manager-ex#1259]
It doesn't work anymore v. 2018.02.26.981

Please fix it

Thanks

**Comment by minakmostoles** [comment]
The free plan to fixerAPI have import changes and it is very basic .Only 1000 API Calls for month
and Base Currencies is only in EUR and the people need to register in https://fixer.io/ to get an api key and it's not very comfortable.  I think is better search another API.
For use this API, we need rewrite all code the this part. That is it better because we need get a json with all rates and save in the database. After we need calculate the rate for your Base Currencies for default

**Comment by MisterY** [comment]
Currency exchange rates can be updated manually as a workaround.

**Comment by minakmostoles** [comment]
> Currency exchange rates can be updated manually as a workaround.

i think in the master version that it isn't working fine the updated manually.In dev version is work fine.
I find another api https://api.exchangeratesapi.io/latest?base=EUR&symbols=USD,GBP 
but i change the url base and the module don´t working.
        String BASE_URL = "https://api.exchangeratesapi.io"; // lasted URL "https://api.fixer.io"
