### ISSUE TITLE
Background synchronization using SAF

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#1294]
#1287 
This is a background job scheduled to perform background synchronization periodically, in line with the settings.
The settings will be hidden until this feature.

**Comment by aprobinda** [comment]
@MisterY do I understand correctly that this feature is required in order to upload newer database file from mobile to a cloud storage, like OneDrive? So as long as this feature is missing, users will keep asking the question below?
Copied from #general
"Please, I have got mmex set up on both desktop windows and Android, using OneDrive for syncing. Working well for data being shared from Windows to Android, however when I add a transaction in Android, it doesn't go back the other way. Have set sync frequency to 30mins, but still no change long after that."
