### ISSUE TITLE
Handle invalid remote Urls

### ISSUE THREAD

**Issue by MisterY** [moneymanagerex/android-money-manager-ex#1295]
Many users report issues with synchronization. The problem, most likely is an invalid remote Url value. This should be the content, using Storage Access Framework, while they have previous remote versions.
Perform a check before opening a database or performing sync and show a message.

**Comment by leodali** [comment]
I still have this issue, updated app to latest version available on Play Store.

**Comment by funrider1** [comment]
a new sync framework (SAF = Storage Access Framework) is implemented (see #1306) and the old kind of sync by MMEX is not availabe anymore. Not all cloud storges support SAF right now. I had to move from DropBox (no SAF Support) to Google Drive (SAF Support). 
You can check which cloud storage is availabe on your android device by using the database open dialog and have a look to the displayed services. Move your database to one of them and open it by using the open dialog. This should fix your problem.

**Comment by sukhoi191** [comment]
Unfortunately, even using Google Drive is not safe in terms of synchronization, at least for me. It's ok until you don't have remote changes and you try to download the database, instead of uploading it. The application crashes in such case. It then happens every time you try to use the "Synchronize" option.
Currently, I have found two workarounds, both are rather bad, but can be used until the problem is resolved.
First - make modifications only on the mobile application.
Second - when the application crashes, you can reset its settings and open the database once again.
I'll try to fix it until the end of the week. I'm really missing the synchronization feature. Unfortunately, I'm working full-time, so I have very limited time, but the good side of this is, I'm a Java developer :)

**Comment by MisterY** [comment]
As can be seen in one of the open issues, the exception crashes the app in the case of conflicts. There has to be a manual intervention, anyway.
Reopening the database will solve it but will also lose local changes. 
The fix for the crash is easy but I'm not sure what to do, if anything, in case of conflicts.

**Comment by sukhoi191** [comment]
The problem is, when I make remote changes on a desktop application and then try to download the database in mobile app by clicking Synchronize button, it seems that the conflict sometimes "creates itself". I am sure that the mobile app cannot detect remote changes and it always uploads its local version, at least in my case (Sony Xperia XZ Premium).

Here's a test case that I've tried on my personal database. For some reason, it doesn't always reproduce.

1. Open clear instance of mobile MMEX (no database selected yet)
2. Select the database in Google Drive
3. Add transaction on the mobile app
4. Synchronize on mobile app - "Database stored successfully", works correctly
5. Add transaction on the desktop app
6. Close the desktop app, wait until the database is synchronized on the Google Drive
7. Synchronize on mobile app - crash

Previously, there was an option in synchronization settings to force download / upload of the database. I would say that user has to make a decision in such case. Perhaps we could show a pop-up with an information about conflict and two options to either use local or remote changes? There seems to be a third possibility, which is a merge of local and remote changes, but I think that it would require a lot of work to implement.

**Comment by leodali** [comment]
Ok, I think I solved my issue with these steps (by the way, I'm using Google Drive for remote sync):
- create a new fresh database;
- select the previous, personal database from Google Drive folders;
- now the database opens correctly;
- ask for manual sync on the mobile app, it finally works!

**Comment by MisterY** [comment]
@sukhoi191, pull requests welcome. Note that any interaction with the user would also have to work later when the background sync is implemented again.
I intend to fix the crash and display the conflict notification but not much else. The users can resolve this manually. Force download is what one gets when the database is opened from the storage provider. Force upload can be done through the provider app. I see no need to reinvent the wheel.

**Comment by sukhoi191** [comment]
@MisterY I really miss the ability to force upload / download the database from the MMEX synchronization settings. I know that it can be done via the provider app, but doing it this way requires a lot of additional work for user.

In case of conflict, what you had to do before was simply clicking an option from synchronization settings.

Correct me if I'm wrong or if there's an easier way to do it, but now if you want to force upload the database, you have to find the local database on the phone, then share it to the provider app, find the correct directory on the cloud and upload it. Same goes for download - find the local database, find the database in the provider app, then download and replace it. It's ok if conflicts happen very rarely, but they were pretty common during my usage.

**Comment by MisterY** [comment]
@sukhoi191, I completely agree with you. It would be more convenient to have more options.

The easier way to force download is to simply use Open Database again. It will overwrite the locally-cached file.
