### ISSUE TITLE
Change stock prices

### ISSUE THREAD

**Issue by JEANPAUL51** [moneymanagerex/android-money-manager-ex#1307]
With the updates of 12 - 13 - 15 February with the change in the prices of stock exchange, the program closes.
Even with the update yesterday 17/02 are the same problems: but what are you updating ???
Please bring back the program as it was before 12/02 !!!!!

**Comment by funrider1** [comment]
I can confirm that issue. Since 12th February App crashes every attempt to edit a stock Price. Current Version of android an ZTE Axon with last version of MMEx

**Comment by MisterY** [comment]
Would anyone bother to submit a log with the actual error? Or, better yet, a pull request with the fix?
I can merge the pull requests in a browser but not much else at the moment.

**Comment by funrider1** [comment]
sorry, i can't fix this because i'm not (yet) familiar with programming ;-) 

here the Logcat snip:

02-18 17:10:54.752 28428 28433 I art     : Do partial code cache 
collection, code=23KB, data=28KB
02-18 17:10:54.752 28428 28433 I art     : After code cache collection, 
code=23KB, data=28KB
02-18 17:10:54.752 28428 28433 I art     : Increasing code cache capacity 
to 128KB
02-18 17:10:57.182 28428 28428 V BoostFramework: BoostFramework() : mPerf = 
com.qualcomm.qti.Performance@5fbc6d9
02-18 17:10:57.182 28428 28428 V BoostFramework: BoostFramework() : mPerf = 
com.qualcomm.qti.Performance@79ff89e
02-18 17:10:57.182 28428 28428 V BoostFramework: BoostFramework() : mPerf = 
com.qualcomm.qti.Performance@ad8f795
02-18 17:10:57.182 28428 28428 V BoostFramework: BoostFramework() : mPerf = 
com.qualcomm.qti.Performance@c0f00aa
**02-18 17:10:57.252 28428 28451 E OpenGLRenderer: void 
android::uirenderer::renderthread::CanvasContext::setSurface(android::Surface 
*) to create EGLSurface 
AtchDlg:com.money.manager.ex/com.money.manager.ex.home.MainActivity
02-18 17:11:03.362 28428 28428 D Typeface: fontPath:
02-18 17:11:03.392 28428 28428 D AndroidRuntime: Shutting down VM
02-18 17:11:03.392 28428 28428 E AndroidRuntime: FATAL EXCEPTION: main
02-18 17:11:03.392 28428 28428 E AndroidRuntime: Process: 
com.money.manager.ex, PID: 28428
02-18 17:11:03.392 28428 28428 E AndroidRuntime: 
java.lang.RuntimeException: Unable to start activity 
ComponentInfo{com.money.manager.ex/com.money.manager.ex.investment.PriceEditActivity}:**

android.view.InflateException: Binary XML file line #34: Binary XML file 
line #34: Error inflating class 
android.support.design.widget.CollapsingToolbarLayout
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2669)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2730)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.app.ActivityThread.-wrap12(ActivityThread.java)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1481)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.os.Handler.dispatchMessage(Handler.java:102)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.os.Looper.loop(Looper.java:179)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.app.ActivityThread.main(ActivityThread.java:6152)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
java.lang.reflect.Method.invoke(Native Method)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: Caused by: 
android.view.InflateException: Binary XML file line #34: Binary XML file 
line #34: Error inflating class 
android.support.design.widget.CollapsingToolbarLayout
02-18 17:11:03.392 28428 28428 E AndroidRuntime: Caused by: 
android.view.InflateException: Binary XML file line #34: Error inflating 
class android.support.design.widget.CollapsingToolbarLayout
02-18 17:11:03.392 28428 28428 E AndroidRuntime: Caused by: 
java.lang.ClassNotFoundException: Didn't find class 
"android.support.design.widget.CollapsingToolbarLayout" on path: 
DexPathList[[zip file 
"/data/app/com.money.manager.ex-2/base.apk"],nativeLibraryDirectories=[/data/app/com.money.manager.ex-2/lib/arm64,

/system/lib64, /vendor/lib64]]
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
java.lang.ClassLoader.loadClass(ClassLoader.java:380)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.view.LayoutInflater.createView(LayoutInflater.java:609)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.view.LayoutInflater.inflate(LayoutInflater.java:518)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.view.LayoutInflater.inflate(LayoutInflater.java:426)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.view.LayoutInflater.inflate(LayoutInflater.java:377)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
com.money.manager.ex.common.MmxBaseFragmentActivity.setContentView(MmxBaseFragmentActivity.java:75)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
com.money.manager.ex.investment.PriceEditActivity.onCreate(PriceEditActivity.java:67)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.app.Activity.performCreate(Activity.java:6728)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2622)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2730)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.app.ActivityThread.-wrap12(ActivityThread.java)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1481)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.os.Handler.dispatchMessage(Handler.java:102)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.os.Looper.loop(Looper.java:179)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
android.app.ActivityThread.main(ActivityThread.java:6152)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
java.lang.reflect.Method.invoke(Native Method)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
02-18 17:11:03.392 28428 28428 E AndroidRuntime: at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by MisterY** [comment]
Thank you, this is the key: 
```
**02-18 17:11:03.392 28428 28428 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.money.manager.ex/com.money.manager.ex.investment.PriceEditActivity}:**

android.view.InflateException: Binary XML file line #34: Binary XML file
line #34: Error inflating class
android.support.design.widget.CollapsingToolbarLayout
```
It is a consequence of the upgrade to the new Google Support libraries. The wizard in Android Studio did not do a good job, it seems, so the namespaces are wrong (from Beta 2 version, I think).
Any form that crashes needs to be manually updated to the correct namespace. In this case CollapsingToolbarLayout.

**Comment by JEANPAUL51** [comment]
At this point, that is <Any form that crashes to update the correct namespace. In this case the culprit is the CollapsingToolbarLayout> who must intervene with the appropriate measures ???

**Comment by MisterY** [comment]
Updating the namespace to com.google.android.material.appbar.CollapsingToolbarLayout.

**Comment by funrider1** [comment]
@misterY do you have an idea when release including this bugfix will be available in f-droid? Thanx

**Comment by MisterY** [comment]
AFAIK, the latest release is already available. If you are still experiencing errors, please post a new log in a separate issue. The cause for this exception has been corrected.

**Comment by funrider1** [comment]
What is the latest release and where it is available?

Release page github tell me: latest release is 2019.02.14.994

Installed in my Phone is 2019.02.14.995 (from f-droid)

In Playstore MMEX is still not available and the beta version is not either.

I can not find the beta in f-droid.

Please help an bring light into the dark :-)

Thanx

**Comment by MisterY** [comment]
Hmm.

F-Droid [page](https://f-droid.org/packages/com.money.manager.ex/) clearly indicates two versions available:
![image](https://user-images.githubusercontent.com/462445/53564766-09dab600-3b58-11e9-8665-3096b23e7a17.png)

The releases are no longer published to GitHub Releases because the signature is different to F-Droid one, and they are available for download from the above F-Droid page directly. This also means I no longer need to have a dev environment and build explicitly in order for the release to become available.
The app is unpublished from Play Store and there are no plans to get to fixing that at the moment.
And, as I mentioned on [Twitter](https://twitter.com/MMEX4Android/status/1097973826502176770):
![image](https://user-images.githubusercontent.com/462445/53564938-705fd400-3b58-11e9-8ef7-541d3645c7d9.png)

I was hoping these were clear. Unfortunately, there are still too many questions coming in and I have very little time to explain the same things over. :(

**Comment by funrider1** [comment]
Hi @Mistery. Thank you, that make it clear and i found the reason. Last Version 995 from PlayStore (installed at my phone) has an other signature than newest Version 996 from f-droid and this preventing the update on my Phone. Now that i understand, it make sense too :-)

I'm looking forward for next beta vor final release .... Thank you for your patience

**Comment by MisterY** [comment]
Ah, yes, that's something I haven't considered. Will send an announcement about that. I had a locally-built version installed for testing and it required the same procedure.
Cheers!

**Comment by MisterY** [comment]
To clarify, the F-Droid releases are built directly by F-Droid, from our source code repository. That guarantees that what is in the binary .apk is exactly what is in the source code.
It also helps in automating the build and release process as nobody else now needs to compile the binaries and upload somewhere to make them available for download.
In addition, F-Droid lists all the published versions, allowing extremely easy downgrade.
And the binary files (.apk) are available from the app's page on F-Droid. 

These are only a few benefits I see at the moment.
