### ISSUE TITLE
sync problem: "both file has been modified"

### ISSUE THREAD

**Issue by ggraziotti** [moneymanagerex/android-money-manager-ex#1356]
On 995 android version on sync with gdrive I have always this problem. How to solve ?

**Comment by derekoharrow** [comment]
I also get this quite often.
I sync using OneDrive, but I know the file hasn't been modified elsewhere as I keep hitting this problem so only update my accounts from my phone now. 
The bigger problem is that once the occurs it is a pain to fix as you can no longer simply overwrite the wrong version, which means deleting files from onedrive etc before sync will work again. 
This has almost had me give up on MMEX sadly.

**Comment by PeterJ504** [comment]
Having the same problem.

**Comment by tfejos** [comment]
Had the same.  nNow deleted all data in settings. Opening from Google Drive is very slow.

**Comment by GabrielKoenig** [comment]
I have also the same issue. I downloaded the latest version from F-Droid on my Samsung S7. And identified the following errors: 

I put an existing .mmdb file on Drobox and Onedrive. (I tried it with both Apps) 

1. After editing something  on the Android App of MMEX. I press the sync button and it syncs perfectly. I close the app properly
2. On my Desktop PC the .mmdb file gets directly updated and I open the database using the desktop version of MMEX all new changes as there. 
3. I make some new changes on the Desktop MMEX and save the database and close the desktop app. It syncs again perfectly. 
4. I reopen on the Android App MMEX and the changes from the Desktop are also there. Thus everything seem to work fine. But when I edit at this stage something and want to sync the error occurs "Conflict: Both file has been modified". 

The same occurs if I try to use two android phones. 

@MisterY You seemed to solved the issue in https://github.com/moneymanagerex/android-money-manager-ex/issues/1278. Is this right? Could you please provide us an updated manual or wiki page how to use the new sync feature (this one is outdated: https://github.com/moneymanagerex/android-money-manager-ex/wiki/Dropbox-synchronization). It is not longer possible to directly choose dropbox syncing.... And I have no idea how to set it up using the Storage Access Framework. 

Thanks for the help.

**Comment by MisterY** [comment]
@GabrielKoenig Dropbox does not seem to have the desire to support the Storage Access Framework, unfortunately.
You are right in that the sync code should store the change values in the sync file but it should be tested more thoroughly. I would recommend debugging the real-world scenario and identifying what causes these values not to match. Setting up a sync framework for multiple services is quite complicated due to the fact that uploading a file requires one to have the **server-side** change timestamp, not local. Therefore, after upload, one must get the change timestamp and store it. For some services this works well, for others it may not.
Unfortunately, I am no longer contributing to the project and have moved to https://cashier.alensiljak.eu.org/ in combination with ledger-cli. This combination seems to offer more options for what I need, as well as full operability on Android.

**Comment by wolfsolver** [comment]
🚀 **First Beta Release Available for Testing!** 🚀

The Record-Level Sync Engine for Money Manager Ex is officially ready for community testing. Say goodbye to file-conflict issues and corrupted database copies!

📦 **What's included in this release:**
* **`mmex-sync.exe` (Desktop Sidecar):** The background sync tool for your PC that works with your existing MMEX desktop application.
* **Modified Android App:** A dedicated mobile build configured to sync in real-time with the cloud API.

📖 **How to get started:**
1. Read the step-by-step setup guide here: [MMEX Sync Documentation](https://github.com/wolfsolver/money_manager_ex_sync_poc/blob/main/README.md)
2. Download the latest artifacts: [Latest Beta Release](https://github.com/wolfsolver/money_manager_ex_sync_poc/releases/latest)

🔒 **How to join the Beta Test:**
Go to [mmex-sync.prudenzano.org](https://mmex-sync.prudenzano.org/), scroll down to fill out the short survey, and request your beta access credentials.

*Note: This is a Proof of Concept (POC) Beta. Please make sure to backup your `.mmb` file before testing!*
