### ISSUE TITLE
Synchronization conflict - both files have been modified

### ISSUE THREAD

**Issue by Patiku** [moneymanagerex/android-money-manager-ex#1369]
I was using manager with Dropbox, then the synchronization was changed and Dropbox did not work. Now I use it with OneDrive but I came across a problem. When I want to synchronize I got an error: "Conflict! Both files have been modified". Earlier I could open Synchronization menu (now it is missing) and just overwrite one of the files. Now it is impossible. Is it a bug or am I doing something wrong?

I would be gratefull for any help.

**Comment by velmuruganc** [comment]
@Patiku , @Savermarshall ,

Along with Conflict msg, now I added following option to force upload or download the changes if it is modified in both the places.
![image](https://user-images.githubusercontent.com/29807533/71571568-f2b27f00-2b00-11ea-8985-3df1ac5ad85b.png)


But we need to manually restart the application due to bug. https://github.com/moneymanagerex/android-money-manager-ex/issues/1330 

Could you please test this and let me know if any issues.

**Installer Package**: [ammx-2019.12.30.1001-beta.apk.zip](https://github.com/moneymanagerex/android-money-manager-ex/files/4009137/ammx-2019.12.30.1001-beta.apk.zip)

**Comment by Savermarshall** [comment]
Thank you very much, the beta version appears making correctly the
synchronization until now.

Il lun 30 dic 2019, 08:08 Velmurugan Cithaiyan <notifications@github.com>
ha scritto:

**Comment by smjohns** [comment]
Is there any way I can get on this beta. I only use Android version of app with Google drive and after a couple of uses it issues a conflict error. Having ability to force upload to Google drive would definitely be a solution as that file isn't being changed apart from when I manually sync from phone.

**Comment by velmuruganc** [comment]
@smjohns, Please download it from below URL.

https://github.com/moneymanagerex/android-money-manager-ex/files/4009137/ammx-2019.12.30.1001-beta.apk.zip

**Comment by smjohns** [comment]
Thank you. I have downloaded it. Weirdly it would not install over the top of the full version so I had to uninstall this so that it would go in. Will this beta upgrade automatically as new versions are released, or will I need to visit a certain page for the latest betas?
