### ISSUE TITLE
Samsung Galaxy TAB A fails to run existing (works on other devices) database

### ISSUE THREAD

**Issue by SJK55** [moneymanagerex/android-money-manager-ex#1394]
Perfectly working Database that's okay on PC, Moto G6 Plus (via Google Drive)
Fails to open and bombs MMEX when opened on a Samsung Galaxy Tab A.

**To Reproduce**
1. Create a database (or use existing)
2. Save to Google drive on PC and access on an Android system
3. Works on Moto G6 Plus
4. Will not work accessing on Samsung Galaxy Tab A

**Expected behavior**
As it is a valid database (not encrypted) What works on PC (Win 10), works on Moto G6 Plus (Android 9) should also work on Samsung Galaxy Tab A which also runs Android 9.

**Screenshots**
When re-installed program opens fine on Samsung Galaxy Tab A but when opening existing Google (or One Drive or Dropbox) whole program goes belly up and fails!
Message is [Money Manager Ex keeps stopping]

**Device Information:**
 - Device: [Samsung Galaxy TAB A]
 - OS: [Android 9]
 - App Version: [2019.02.19.995]

**Additional context**
Re-installed works fine until I open existing database! Then bombs!
My database is around 7Mb.

**Comment by mik13ST** [comment]
I am having similar problems with recent (2019) releases (basically all F-Droid available releases). The app just cannot open it's own database or something like that. I am experiencing these problems on two devices of different Android version (6 and 7) so there is something going on. I temporarily solved the issue by downgrading to [2018.11.15.987](https://github.com/moneymanagerex/android-money-manager-ex/releases/tag/2018.11.15.987).

As a next step I could determine the exact version that has these problems or even do a `git bisect` to pin point the exact commit. I should try to reproduce this bug in the Android emulator so the issue is easy to reproduce.

I will see if I get back to this.

**Comment by mik13ST** [comment]
It seems to happen right between the `2018.11.15.987` and `2019.01.09.989` releases/tags. Git bisect is not possible because the builds are often failing in these commits. It probably has something to do with the storage API (see 4a79fadd9) that was changed between those two releases. I will try picking the file using a different file manager (currently using [MiXplorer from XDA](https://forum.xda-developers.com/showthread.php?t=1523691) - not associated with Xiaomi in any way) or possibly in the Android emulator.

**Comment by SJK55** [comment]
Seems I'm not the only one having this problem as someone else is having similar problem.
I hope it can be fixed. 
PS My Samsung Tablet updated to 10 recently and I hoped that might 'fix' this problem but status quo is the same. Will not load existing populated database. Even if stored on tablet itself!

**Comment by SJK55** [comment]
I wonder why this was closed as it has never been resolved. This also applies to the lack of continued support for the Android version.

**Comment by guanlisheng** [comment]
It's just regular cleanup as it has had no activities over 2 years.

**Comment by SJK55** [comment]
Ok. Will anyone ever look into these issues? Having the Android crossover platforms was one of the main draw cards for me.
Thanks for replying.

**Comment by guanlisheng** [comment]
maybe you can try the latest release package (after your database back up).
