### ISSUE TITLE
Economic competence of the expenses

### ISSUE THREAD

**Issue by br1z750** [moneymanagerex/android-money-manager-ex#1416]
Hi all,
Is it possibile to create a new view (maybe inside the "Resoconti" Tab) that give the possibility to split expenses (and income) based on the competence date?
Example: i buy a car today, we know that for the entire year I'm in loss of i see the "resoconto" expenses/income.

**Possibile solution**
For each expenses (or income) insert a flag (competence date) that open a possibility to insert a date (from / to) where the user indicate the competence of the expense.
Inside the view "resoconti" the user can select the possibility to view by competence date the expenses and income (of present) otherwise use the date inserted for the income/expenses

What do you think about that?

Thanks a lot for the support
B

**Comment by tactilis** [comment]
@br1z750
> What do you think about that?

To be honest, I'm having a lot of difficulty understanding what you mean - and maybe others are having the same difficulty as well. Partly it's a problem of Italian to English translation, and partly it's because you haven't provided enough information about your proposed feature.

Could you give a some clear examples please showing expense transactions with dates, amounts, and the new from/to dates field that you are asking for? And then, using these transactions, some example of _exactly_ what you would expect to see in the new view you are requesting?
