### ISSUE TITLE
Add the ability to have zero amount transaction

### ISSUE THREAD

**Issue by jeepcook** [moneymanagerex/android-money-manager-ex#1491]
As it exists in the windows version, add the ability to create a null opération (0 euro), or to have the result of an operation with more than one transaction (ventilated) with a result of zero.
It's useful I think.

Thanks

**Comment by jeepcook** [comment]
Ok but even if you choose void, you can't validated the transaction because the amount is 0 euro in your screenshot.

Another case is to use split transactions with a negative transaction with an amount and a positive transaction with the same amount, so the total is 0 euro and you can't validate the transaction. An error message say something like "the amount has to be positive..."

Hope I am clear.

**Comment by luisdev** [comment]
What do you want to use null transactions for?

Why would you record a transaction that doesn't have a monetary value in MMX?

And is NULL = 0 in your case? 😲

**Comment by jeepcook** [comment]
I want to speak about 0 euro amount, sorry with the confusion with null.
I'd like to have the ability to have the result of transactions in the same operation with the total amount of 0.
Example, when you have a pré-paid opération which is cancelled or refund later. So it's the same operation but with 2 transactions and the result can be positive or 0.
And this can be done with mmex pc so why not whith android version?

**Comment by luisdev** [comment]
Are both the "+" and the "-" transactions always recorded with the same date? If not, isn't it better to use two separate transactions so that you can record the correct dates?

If the dates aren't significant, then why not use a split transaction?
You add two items to the split transaction - one for the "+" event and another for the "-" event. And the nice thing about a split transaction is that you don't have to add both the  "+" and "-" events at the same time, assuming they are triggered at different times. You can create the transaction with just the  "+" or "-" event and add the other one o the split transactions later.
The only thing you can't do is use different dates for each event.

**Comment by jeepcook** [comment]
I know all of that, I'm using mmex for a lot of years. But if the result of the split transactions is 0, it's impossible to validate because 0 is forbidden. Just do a try and you will see.

**Comment by luisdev** [comment]
Ok. I see your point - a 0 amount is not allowed.

**Comment by jeepcook** [comment]
Thanks for this update. Not in the last 2024.02.08.1018 so will be in the 1019 version?

**Comment by guanlisheng** [comment]
exactly, @jeepcook.
