### ISSUE TITLE
Continious rotation of arrows when synchronization is enabled

### ISSUE THREAD

**Issue by jeepcook** [moneymanagerex/android-money-manager-ex#1524]
There is an annoying thing when synchronization is enabled. The 2 round arrows are rotating all the time and never stop.
![Screenshot_2024-01-14-19-37-36-244_com money manager ex-edit](https://github.com/moneymanagerex/android-money-manager-ex/assets/17811804/eee69e1b-38fb-4d67-a6ca-fceea9741638)

My configuration:
- Synchronization enabled
- Synchronize on startup enabled
- Synchronize immediately the database if modified is enabled
- Remote file is on gDrive

The synchronization is ok but the comportment of this arrows is annoying.

Thanks for the fix.

Regards.

**Comment by luisdev** [comment]
Yes, the rotating arrows imply that a synchronization is in progress, when in fact no sync is active. This eventually makes you think that something is wrong with the sync process.

**Comment by guanlisheng** [comment]
@luisdev and @jeepcook , can you verify it for v2024.02.08 from f-droid?

**Comment by luisdev** [comment]
It seems to be fixed in 2024.02.15 (1019). I can't get the sync icon to show in that build.

When I tap the Synchronize option on the message, I get a "Database stored successfully" message.

But I'm not sure if my Synchronize setup is correct. I tried Syncthing and OneDrive, but it doesn't seem to be working... Probably because I didn't read the instructions correctly! 😉

I didn't check build 2024.02.18.

**Comment by guanlisheng** [comment]
I think it is working base don the success message.

**Comment by jeepcook** [comment]
Hi,
I have issues on my poco smartphone. I think I will have to reset it. I will do a feedback for ammex after that.
