### ISSUE TITLE
Can't open any transaccion (crash)

### ISSUE THREAD

**Issue by Sergius7** [moneymanagerex/android-money-manager-ex#1671]
**Describe the bug**
On a existing DB I use daily, opening any transaction crashes the App.

**To Reproduce**
1. Go to 'any account'
2. Click on 'any existing transaction'
3. Application crashes

**Expected behavior**
Just open the transactions, edit, create new ones, etc. App become unusable.

**Screenshots**

**Device Information:**
 - Device: Samsung A53
 - OS: Android 14
 - Storage: Google Drive
 - Synchronization: Sync on Start
 - Encrypted: No
 - App Version: Affected versions: 2024.04.15.1027 & 2024.04.16.1028. Rollback to 2024.04.01.1026 solved the issue.

**Additional context**
Full App reinstall + data delete and cache clear do not solved the issue.

**Comment by guanlisheng** [comment]
we can't reproduce the crash issue. can you share more?

**Comment by Sergius7** [comment]
Has to be something triggered by my DB or environment but only triggered with latest versions.. what else can I provide?  a crashdump? (how can I do that?)

**Comment by guanlisheng** [comment]
About -> LOGCAT might help on logs.

also, can you reproduce with a tiny dataset?

**Comment by xraynaud** [comment]
I believe I have the same problem. Here is the DEBUG logcat of the session. 
I clicked on a transaction at around 10:40:15.

This logcat exerpt is obtained by clicking on the "share" button in the logcat window. The big LOGCAT button on the info page triggers a "Error: Failure from system" message.

I'll see during the day if I can make a  tiny dataset that triggers the crash.

E/ 04-21 10:40:09.649 oney.manager.ex(16986): Not starting debugger since process cannot load the jdwp agent.
E/ 04-21 10:40:09.818 QT      (16986): [QT]file does not exist
E/ 04-21 10:40:09.825 OpenGLRenderer(16986): Device claims wide gamut support, cannot find matching config, error = EGL_SUCCESS
W/ 04-21 10:40:09.825 OpenGLRenderer(16986): Failed to initialize 101010-2 format, error = EGL_SUCCESS
W/ 04-21 10:40:10.035 OpenGLRenderer(16986): Unknown dataspace 0
E/ 04-21 10:40:10.078 FBI     (16986): Can't load library: dlopen failed: library "libmagtsync.so" not found
W/ 04-21 10:40:13.774 WindowOnBackDispatcher(16986): OnBackInvokedCallback is not enabled for the application.
W/ 04-21 10:40:13.774 WindowOnBackDispatcher(16986): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
E/ 04-21 10:40:16.279 Android-Iconics(16986): Can't init: com.mikepenz.mmex_icon_font_typeface_library.MMEXIconFont
E/ 04-21 10:40:16.438 AndroidRuntime(16986): FATAL EXCEPTION: main
E/ 04-21 10:40:16.438 AndroidRuntime(16986): Process: com.money.manager.ex, PID: 16986
E/ 04-21 10:40:16.438 AndroidRuntime(16986): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.money.manager.ex/com.money.manager.ex.transactions.CheckingTransactionEditActivity}: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 81
E/ 04-21 10:40:16.438 AndroidRuntime(16986): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4164)
E/ 04-21 10:40:16.438 AndroidRuntime(16986): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
E/ 04-21 10:40:16.438 AndroidRuntime(16986): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/ 04-21 10:40:16.438 AndroidRuntime(16986): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
E/ 04-21 10:40:16.438 AndroidRuntime(16986): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
E/ 04-21 10:40:16.438 AndroidRuntime(16986): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
E/ 04-21 10:40:16.438 AndroidRuntime(16986): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/ 04-21 10:40:16.438 AndroidRuntime(16986): 	at android.os.Looper.loopOnce(Looper.java:230)
E/ 04-21 10:40:16.438 AndroidRuntime(16986): 	at android.os.Looper.loop(Looper.java:319)
E/ 04-21 10:40:16.438 AndroidRuntime(16986): 	at android.app.ActivityThread.main(ActivityThread.java:8893)
E/ 04-21 10:40:16.438 AndroidRuntime(16986): 	at java.lang.reflect.Method.invoke(Native Method)
E/ 04-21 10:40:16.438 AndroidRuntime(16986): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
E/ 04-21 10:40:16.438 AndroidRuntime(16986): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
E/ 04-21 10:40:16.438 AndroidRuntime(16986): Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 81
E/ 04-21 10:40:16.438 AndroidRuntime(16986): 	at java.lang.String.checkBoundsBeginEnd(String.java:4466)
E/ 04-21 10:40:16.438 AndroidRuntime(16986): 	at java.lang.String.substring(String.java:2517)
E/ 04-21 10:40:16.438 AndroidRuntime(16986): 	at com.money.manager.ex.transactions.EditTransactionCommonFunctions.initAttachmentControls(EditTransactionCommonFunctions.java:736)
E/ 04-21 10:40:16.438 AndroidRuntime(16986): 	at com.money.manager.ex.transactions.CheckingTransactionEditActivity.initializeInputControls(CheckingTransactionEditActivity.java:383)
E/ 04-21 10:40:16.438 AndroidRuntime(16986): 	at com.money.manager.ex.transactions.CheckingTransactionEditActivity.onCreate(CheckingTransactionEditActivity.java:122)
E/ 04-21 10:40:16.438 AndroidRuntime(16986): 	at android.app.Activity.performCreate(Activity.java:8944)
E/ 04-21 10:40:16.438 AndroidRuntime(16986): 	at android.app.Activity.performCreate(Activity.java:8913)
E/ 04-21 10:40:16.438 AndroidRuntime(16986): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
E/ 04-21 10:40:16.438 AndroidRuntime(16986): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
E/ 04-21 10:40:16.438 AndroidRuntime(16986): 	... 12 more
E/ 04-21 10:40:26.684 oney.manager.ex(17305): Not starting debugger since process cannot load the jdwp agent.

**Comment by guanlisheng** [comment]
thanks, both.

Can you share your database's remote and local path, i think it is related.

**Comment by xraynaud** [comment]
here they are: 
local: /storage/emulated/0/Android/data/com.money.manager.ex/files/databases/gt-9300.mmb
remote: content://org.nextcloud.documents/document/480acfbda080395f1bf85b38b061b14f%2F581

**Comment by awmhove** [comment]
I am facing same issue on Samsung A04s.
I can't create new transaction, the app crushes. I have cleared cache but didn't help. It started with v2024.04.15 then Upgraded to v2024.04.16 but didn't solve the issue. 

Logcat is showing error: failure from the system.

**Comment by guanlisheng** [comment]
I c.  

it is indeed a bug during retrieving the remote file directory.  will roll out a bug fix release shortly.

**Comment by guanlisheng** [comment]
any guys are willing to verify the fix via https://drive.google.com/file/d/161uzz5G53tqsrYAzsHHOr0C8qVMuI8xm/view?usp=sharing

**Comment by Sergius7** [comment]
It is working for me now!

**Comment by guanlisheng** [comment]
thanks, @Sergius7 

will make it available for both GitHub and F-Droid soon.
