### ISSUE TITLE
Bug on + button

### ISSUE THREAD

**Issue by Prum55** [moneymanagerex/android-money-manager-ex#1677]
When I want to add a new transaction pushing the + button, the app cancels and closes itself !!!

**Device Information:**
 - Device: Samsung S21 5G
 - OS: Android 14
 - Storage: Phone storage 256
 - App Version: 2024.04.16 (1028).

**Comment by smjohns** [comment]
This issue is much bigger. My app also crashes when trying to edit an existing entry too. Worse still, I've tried completely uninstalling the app and installing 2024.04.15, which was previously working fine and that is also crashing too.

Hope you can fix this issue quickly and that it hasn't corrupted my database. 

Mines a Samsung S22 UK chip set running Android 14. Anonymous logging is enabled.

Have tried clearing cache/data and returning to older version of dB but still crashing.

**Comment by smjohns** [comment]
I've now returned to version 2024.04.01 and the crashing has stopped. Phew. 

Hopefully you can work out what has caused this and may be worth removing the 15/16 from FDroid?

**Comment by smjohns** [comment]
Just tried upgrading directly from 2024.04.01 to 16 and crashing returned immediately. Had to clear app data and fully uninstall and then return to 01 to restore a working app.

**Comment by Prum55** [comment]
I just loaded and upgraded from 2024.04.01 and it works ! And I locked future updating for the moment... Thanks and have a good night !

**Comment by guanlisheng** [comment]
thanks all, it was a bug and fixed in the upcoming release 
#1671

**Comment by guanlisheng** [comment]
@Prum55 , @smjohns 
can you try out the latest release v2024.04.21 (1029)
https://f-droid.org/packages/com.money.manager.ex/

**Comment by smjohns** [comment]
Not seeing it as yet. F Droid still only has 2024.06.16 available.

**Comment by smjohns** [comment]
It has just upgraded to 2024.04.21 on my phone and I can confirm that the crashing has now stopped and I can again add/edit transactions. Thank you for fixing this so quickly !!

**Comment by Prum55** [comment]
Great ! It works with the last release v2024.04.21 (1029) ! Thanks all !

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
