### ISSUE TITLE
Scheduled transactions: Related to 1719

### ISSUE THREAD

**Issue by rmkhalfay** [moneymanagerex/android-money-manager-ex#1729]
Issue 1719 was closed. 

Thank you for the efforts taken. I have s23 ultra and Android 14. I tried 1034 beta you sent, it gives me a notification but does not give a choice whether to enter the scheduled transaction or not. Sometimes although the transaction is scheduled it is not executed due to some delay.

I would like if it asks me can I enter this transaction or not? Or alternatively when we setup scheduled transaction we can have toggle switch 1. Manual or 2. Automatic entry

**Comment by wolfsolver** [comment]
Hi all, switch is available in setting (I think that default need to be set as false to prevent autoexecution on first run).

A generic consideration on schedule transaction: In querybilldeposit field REPEATS has mutiple mining in desktop app:
* 0## ==> normal execution, transaction IS NOT Automatic entered or Notified 
* 1## ==> Transaction is notified on due date, but NOT automatic execution
* 2## ==> Transaction is AUTOMATIC entered (and not notified)
I thinks that this beavhoiur need to be set also in mobile app. Taking a look to code main during loop at cursor a switch need to be implemented:

```
switch(REPEAT / 100 ) {
  case 0: // ignore recurring
      break; //optional
  case 1: // set in popup
      break; //optional
  case 2: // autoexecute  
}
```

**Comment by jorgeEF** [comment]
Hello again.. can you please set "execution scheduled transaction overdue" disabled by default? It's the behavior the app always had.. I'm asking for it because today I had more than 10 overdue transactions that I must manually complete because sometimes the date passes as it is not a written in stone date.. what happened is that I updated the app and as the date was overdue it confirmed all these transaction because defauot setting is enabled to automatically process the transaction at overdue.. I don't want it to happen again in a future update please, it takes hours to fix my db again when transactions ocurrs automatically.

**Comment by wolfsolver** [comment]
I have add Schedule Transaction mode.

1) now in edit you can choise mode (Manual, Prompt, Auto) in according with Desktop version
2) Only Automatic transaction will be posted if posting is enable in setting

![image](https://github.com/user-attachments/assets/66a4096f-cbcf-4155-b124-e85ba4b07853)

**Comment by rmkhalfay** [comment]
Thank you Sir. Hope the version is released soon!
