### ISSUE TITLE
Handle split transfers

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#173]
Question/request from a user:
If split transaction contains transfers (possibly even only transfers), this should be supported. (?)

**Comment by MisterY** [comment]
related issue: https://github.com/moneymanagerex/moneymanagerex/issues/461

**Comment by guanlisheng** [comment]
I would like to keep existing simple one that doesn't support split transfer,what do you guys think?

**Comment by MisterY** [comment]
The only case where I can imagine a split transfer would be something like a salary record. For pretty much everything else, I find it difficult to have a split transfer instead of two distinct transactions. In a bank transfer it is impossible. Cash transfer is also difficult at best.
So, I am undecided on this one yet.
While I understand the user's concern, I would love to see a concrete example.

**Comment by CraftingGamerTom** [comment]
I agree we should keep this simple. But I see the value in handling salaries being split and handling 'cash back'
Possible compromises

- Add optional tax field to a transaction - but would likely require DB schema changes
- Feature for creating transactions in bulk
- Feature for 'cash back' on a transaction that could create multiple transactions with some information like the charge for the cash back and the amount received. But this will likely be wildly complex
