### ISSUE TITLE
Endless synchronisation and crash

### ISSUE THREAD

**Issue by Alexandrejoe** [moneymanagerex/android-money-manager-ex#1732]
Using v1033 (2024.06.14 from Fdroid), when i open the app, it crash at first then it displays a message saying the file is being sync for few minutes and crash. Can't use the app anymore. 
I have emptied the cache memeory and restart the app/phone without any results.

Any idea?

![Screenshot_20240629_095424_Gallery](https://github.com/moneymanagerex/android-money-manager-ex/assets/17069681/bbefe6ce-8c5b-4a15-88a3-b59663e1c4ef)

**Comment by guanlisheng** [comment]
how about re-install the app?

**Comment by bluewaves-it** [comment]
Hello,
I am experiencing the same issue.
I am using version 2024.06.14 too, but I had the same problem also with previous versions.
The problem is fixed if I reinstall the app (it happens quite frequently so I learned the workaround), but it would be nice if someone had a look at it.

Maybe it would be also enough to put a timeout on the synchronizing operation.

OnePlus Nord device with Android 12, synchronizing with Onedrive account.

**Comment by wolfsolver** [comment]
Hi all, there is a know issue using OneDrive, depend to OneDrive itself and not to app (I have same issue with keepassx).
The problem is that after 48h (more or less) token expire and the URL change in something like ".../?refresh....". 
A quick solution is to set app with sync on load, and then is failed (or crash) clear data and reopen dB.
