### ISSUE TITLE
Display the exchange rate on transfers in different currencies

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#227]
On the New/Edit Transaction screen.
When doing a transfer between different currencies, it is often very useful to see the exchange rate based on the amounts from and to. 
We could also allow the user to save this rate as the actual exchange rate for the given currency. This would work only in cases when one of the currencies is the base currency.

Related to #312

**Comment by marty008** [comment]
This raises interesting questions.
1. MMEX does an update of current Xchnge rate from a source. (I am not interested in the source but use rate as a guide for my forward short-term budget forecast of transfers between countries). When the transfer actually happens, it certainly would be useful to display the calculated rate based upon actuals. 
2. I am not sure of the second comment, since, when the transaction is reconciled, the calculated rate is the actual rate, is it not?
3. For my short-term budgeting, my recurring transactions, which I pre-enter up to 3months ahead, default to the current rate. From my personal point of view, I would like to assume adverse movement of rates, say by decreasing by 1% for each month ahead, but that is no doubt an extreme wish

**Comment by MisterY** [comment]
To clarify point number 2: the idea was to display the rate between the from and to amounts in the New Transaction form. The option to save the rate would store the rate value into the Currency record so it is reused later. This is because, when a Transfer is selected, it is enough to enter the From amount and the Destination amount will be automatically calculated based on the exchange rate of the destination currency.

**Comment by marty008** [comment]
On 08/07/2015 22:54, Alen Siljak wrote:
>
> To clarify point number 2: the idea was to display the rate between 
> the from and to amounts in the New Transaction form. The option to 
> save the rate would store the rate value into the Currency record so 
> it is reused later. This is because, when a Transfer is selected, it 
> is enough to enter the From amount and the Destination amount will be 
> automatically calculated based on the exchange rate of the destination 
> currency.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/moneymanagerex/android-money-manager-ex/issues/227#issuecomment-119728191>.
>
Alen, that is totally understandable, but one does not always get the 
exchange rate you have obtained!

Banks give a very poor rate compared with , say, the ECB rate, and there 
are numerous other ways of getting better value.

I use Currencyfair, and if you look for them on Facebook, they share an 
independant survey which tracks and compares all the different ways, for 
the countries and currencies they support

  I am also able to receive a UK state pension paid in pounds but 
received direct in euros in my local bank, and this is usually the 
closest to the ECB rate.

Finally, to repeat my point, I do not know where you get your rates 
from, but have no problem in accepting them as a guide value for forward 
budgeting. When I get an actual value in my account, I make the 
amendment to the transaction, so it would be _nice _to have the 
transaction show the effective rate .

As a postscript, I have set up a dummy account in pounds, to show all 
pound-based pensions that are received in euros each year, and show a 
transfer to my bank account on the expected date, which is converted by 
MMEX to euros, using your rate. This allows 3 monthly budget in a 
straight-forward way

Example  Pension  of 100 pounds paid every 4 weeks into dummy account, 
status reconciled
100 pounds transferred to local euro bank account the next day, with 
conversion to euros, is shown as 130 euros in my bank account, status none
When the money actually arrives in the bank account as 128.54, I go back 
to the transfer, change the received value, and mark it as reconciled

Hope all this helps

Regards

Martin
