### ISSUE TITLE
balance display on bank account resume shows multiple decimals

### ISSUE THREAD

**Issue by davi-bittencourt** [moneymanagerex/android-money-manager-ex#488]
Hello,

The resume of bank account have a problem.
It,s listing a value without rounding. For example, 1500,99999999901. Tested on galaxy s4 mini. Android 4.4.2.

**Comment by MisterY** [comment]
Thanks for the report. Do you have a base currency set?
There was a change recently where we removed the rounding because there are currencies with 3 decimal places and it is not correct to round those numbers to 2 decimals.
Now, the formatting is based on the default currency settings. Let me know if this is the case.
Also, if you could post a screenshot of the location where this is manifested, that would be great.

**Comment by davi-bittencourt** [comment]
Fixed on last update. Tks

**Comment by MisterY** [comment]
Thanks for the confirmation!
