### ISSUE TITLE
Navigation Drawer Item DropboxSyncronization shows up only on App restart

### ISSUE THREAD

**Issue by alex-gee** [moneymanagerex/android-money-manager-ex#632]
I noticed that if a setup the synchronization with dropbox it will take until the next "onCreate()" of MainActivity.java until the corresponding item is show in the navigation drawer. This has no really negative effect, however in my opinion is reduces the user experience because if the user has just setup this feature it can be assumed the user wants try it immediatly.

Excuse my bad english.

**Comment by MisterY** [comment]
You are right. There are several issues that would be resolved by restarting the Main Activity, like changing the theme, adding/removing drawer menus, or switching a database (this one is the most difficult because of the asynchronous nature of data access). Unfortunately, I have not yet found a satisfactory way to restart the activity under all the supported platforms (4.1+).

Perhaps this particular issue can be solved by recreating the drawer only. This should be tested first. It might be fairly easy to implement by firing an event, catching it in the Main Activity, and recreating the drawer (by destroying it first and then running the creation function again).

**Comment by MisterY** [comment]
Deprecated since #1278
