### ISSUE TITLE
Unable to connect to dropbox using firefox45 browser on android

### ISSUE THREAD

**Issue by Geoplace** [moneymanagerex/android-money-manager-ex#747]
When I try to connect to dropbox using firefox 45.0.1 on android all the process in the browser is done succesfully (I see in dropbox the app Linked)but
Money Manager App doesn't recognize the syncronization so it remains with the other dropbox menu options disabled.

I did the process with the stock browser and i works fine.

**Comment by MisterY** [comment]
Did you try to unlink and then link to Dropbox again? This could be caused by the fact that the Dropbox app key has changed. Just wondering.

**Comment by Geoplace** [comment]
Yes I unlink from dropbox inside the app and try to connect and after entering the drop box website and make sucessful link the app didn't recognized.

I also enter dropbox website in a PC and delete the link to the app and the make the steps to connect without success until I try a different browser.

**Comment by MisterY** [comment]
Thanks for the info. I'm not really sure what can be done in that regard. Authentication is handled completely by the Dropbox library and the Android system. MMEX simply receives an event when the process is complete.
I will try to reproduce this in an emulator. It does not happen if Dropbox app is installed as the request automatically gets forwarded to that instead of a browser.

**Comment by Geoplace** [comment]
Right, I don't have dropbox app installed.
Maybe We have to contact mozilla to report the issue.

**Comment by MisterY** [comment]
That certainly would not harm.

**Comment by MisterY** [comment]
Not directly related to the app.
