### ISSUE TITLE
Unable to link my account to Dropbox

### ISSUE THREAD

**Issue by ravisharma117** [moneymanagerex/android-money-manager-ex#860]
Hi,

I am trying to link my android device to Dropbox. When I have clicked on "Link to Dropbox". Then it takes me to broswer -> I allow the app, but nothing happens. Options inside Dropbox menu (such as Dropbox file) are still disabled.

I am using version 2016.06.01 (Build 844).

Can you help me to figure out issue?

Thank you

**Comment by MisterY** [comment]
Hi! I've seen reports that authentication does not work with Firefox, for example. You can try using the built-in browser. Another option would be to install Dropbox client.
The third option would be to try out the current Beta version as the synchronisation library has changed completely. Any feedback would be appreciated.

**Comment by ravisharma117** [comment]
Thank you for feedback. I have already tried first 2 options which failed for me

Now I have tried with "The third option", but still error out while connecting to dropbox. I have send you feedback email to android email id.

I am still unsuccessfully to sync. So if you have some solution, Please send it to me.

**Comment by MisterY** [comment]
Unfortunately, this does not seem to be something I can fix. I could only perhaps handle the exception better so that the app does not crash but this is a cosmetic adjustment.
There seems to be an error during the Dropbox log-on process, inside the Dropbox or CloudRail libraries.
Perhaps there is a firewall that blocks certain network traffic. You can try connecting to a different network (Wi-Fi) and see if that helps. Perhaps the issue is only during the log-in.
Please let me know if you make any progress.

************ CAUSE OF ERROR ************
java.lang.RuntimeException: ServiceCode Error in function validateResponse at 9
at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:108)
at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:42)
at com.cloudrail.si.services.Dropbox.login(Dropbox.java:799)
at com.money.manager.ex.sync.SyncManager$2.run(SyncManager.java:329)
Caused by: java.lang.IllegalArgumentException: command: string.indexOf parameter sourceString is not from type String!
at com.cloudrail.si.servicecode.commands.string.IndexOf.execute(IndexOf.java:37)
at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:84)

**Comment by MisterY** [comment]
Will try to handle the effects in #862
