### ISSUE TITLE
Use sync framework 

### ISSUE THREAD

**Issue by alensiljak** [moneymanagerex/android-money-manager-ex#950]
Use the framework provided by android to schedule and perform the automatic synchronization instead of a manual wake-up call.

References:
- http://blog.udinic.com/2013/07/24/write-your-own-android-sync-adapter/
- https://github.com/Udinic/SyncAdapter
- https://developer.android.com/training/sync-adapters/index.html
- http://chariotsolutions.com/blog/post/android-data-sync/
- https://software.intel.com/en-us/android/articles/handling-offline-capability-and-data-sync-in-an-android-app-part-2

**Comment by MisterY** [comment]
Synchronization should be done by an external party.

**Comment by wolfsolver** [comment]
@guanlisheng I think this issue is old and new SAF is in place. 

Can this be closed?

**Comment by dl200010** [comment]
I think the best way to fix sync for Syncthing would be to use the mmb file in the Syncthing folder, instead of copying to MMEX's folder in Android. I always have issues with syncing, because it doesn't save out to the Syncthing folder. Syncthing will automatically upload any changes, but there is no changes to the file it is looking at, and if the Syncthing file changes then MMEX complains about being out of sync.

**Comment by guanlisheng** [comment]
hi @dl200010, so far we haven't found a proper way to use mmb file out of android/data.

i believe you are familiar with current [MMEX's arch ](https://forum.moneymanagerex.org/viewtopic.php?p=24565#p24565), and I would like to understand more about your sync issues.

**Comment by dl200010** [comment]
> hi @dl200010, so far we haven't found a proper way to use mmb file out of android/data.
> 
> i believe you are familiar with current [MMEX's arch ](https://forum.moneymanagerex.org/viewtopic.php?p=24565#p24565), and I would like to understand more about your sync issues.

The issue I have the most is that the app doesn't keep both files in sync. I always end up with conflicts because the Android app just opened the database (without any changes from me) but never syncs to the Syncthing folder and then the desktop app changes the database. Next time I open the app it complains about being out of sync. I am not personally familiar with the MMEX's arch. I haven't actually looked into the code. I don't even use the android app, because this sync issue makes it useless for me. I just decided to check it out seeing that there is development again.

**Comment by guanlisheng** [comment]
wow, looking forward to your real feedback and you can check it out via[ f-droid](https://f-droid.org/packages/com.money.manager.ex/) now

**Comment by dl200010** [comment]
> wow, looking forward to your real feedback and you can check it out via[ f-droid](https://f-droid.org/packages/com.money.manager.ex/) now

I have checked out the one on F-Droid. 2/2/2024 version, but I see 2/8 exists. It still has the same problem. Constantly dealing with conflicts make it useless for me.

**Comment by guanlisheng** [comment]
sure thing that the new app cannot fix the existing conflicted data... it is trying the base to sync data and avoid conflict.

The data should be fixed first (you can choose either as base or ground true) then can have an apple to apple...

**Comment by guanlisheng** [comment]
here you go some practices from other MMEX + Syncthing users
https://forum.moneymanagerex.org/viewtopic.php?p=24518#p24518

**Comment by guanlisheng** [comment]
anyway, this is a little bit off-topic and going to close this issue.

**Comment by dl200010** [comment]
> sure thing that the new app cannot fix the existing conflicted data... it is trying its best to sync data and avoid conflict.
> 
> The data should be fixed first (you can choose either as the base or ground truth) then can have an apple to apple...

I have fixed the data by forcing MMEX to pull from remote. That way it got the data from Syncthing. I still get the same issue when I installed 2/2/2024. I might try newer versions, but the sync issue is still there in 2/2.

**Comment by guanlisheng** [comment]
hi @jeepcook, can you help here? this inquiry is almost identical to yours. 
also, @dl200010 great if we can a dedicated thread in project forum or issue in github.

**Comment by jeepcook** [comment]
Hi,

@dl200010 , tell me when the thread is open or issue and give me the link.

Thanks

**Comment by dl200010** [comment]
https://github.com/moneymanagerex/android-money-manager-ex/issues/1571
